# Generated by Django 5.2 on 2025-06-01 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=10)),
                ('l_name', models.CharField(max_length=10)),
                ('emp_pass', models.CharField(max_length=20)),
                ('emp_email', models.EmailField(default='example@email.com', max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('city', models.CharField(max_length=10)),
                ('sal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('dept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paykaro_app.department')),
                ('man_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paykaro_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('sal_range', models.CharField(max_length=30)),
                ('dept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paykaro_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('payroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_period_start', models.DateField(blank=True, null=True)),
                ('pay_period_end', models.DateField(blank=True, null=True)),
                ('leave_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('F', 'Failed')], default='P', max_length=1)),
                ('generation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('report', models.FileField(blank=True, null=True, upload_to='payroll_reports/')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paykaro_app.employee')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payrolls', to='paykaro_app.employee')),
            ],
            options={
                'ordering': ['-generation_date'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('reason', models.CharField(default='', max_length=20)),
                ('emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paykaro_app.employee')),
                ('payroll_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paykaro_app.payroll')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.AutoField(primary_key=True, serialize=False)),
                ('basic', models.DecimalField(decimal_places=2, help_text='Basic salary', max_digits=10)),
                ('DA', models.DecimalField(decimal_places=2, help_text='Dearness Allowance', max_digits=10)),
                ('HRA', models.DecimalField(decimal_places=2, help_text='House Rent Allowance', max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, help_text='Bonus amount', max_digits=10)),
                ('income_tax', models.DecimalField(decimal_places=2, help_text='Income tax deducted', max_digits=10)),
                ('PF', models.DecimalField(decimal_places=2, help_text='Provident Fund contribution', max_digits=10)),
                ('health_ins', models.DecimalField(decimal_places=2, default=1000, help_text='Health insurance deduction', max_digits=10)),
                ('emp_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='paykaro_app.employee')),
            ],
        ),
        migrations.AddField(
            model_name='payroll',
            name='salary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paykaro_app.salary'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['employee', 'pay_period_start', 'pay_period_end'], name='paykaro_app_employe_7f1fec_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['status', 'generation_date'], name='paykaro_app_status_6ea6aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'pay_period_start', 'pay_period_end')},
        ),
    ]
