# Generated by Django 5.2 on 2025-05-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paykaro_app', '0002_alter_employee_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_email',
            field=models.EmailField(default='example@email.com', max_length=254, unique=True),
        ),
    ]
