# Generated by Django 5.2 on 2025-06-01 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paykaro_app', '0002_alter_employee_man_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paykaro_app.job'),
        ),
    ]
