# Generated by Django 5.2 on 2025-05-09 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paykaro_app', '0003_employee_emp_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='JobDepartment',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('sal_range', models.CharField(max_length=30)),
                ('dept_name', models.CharField(max_length=15)),
                ('man_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paykaro_app.employee')),
            ],
        ),
    ]
