# Generated by Django 5.2 on 2025-05-10 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paykaro_app', '0005_salary_leave_emp_id_leave_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='salary_id',
        ),
        migrations.AddField(
            model_name='salary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('payroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('tot_amt', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('report', models.FileField(blank=True, null=True, upload_to='payroll_reports/')),
                ('date', models.DateField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paykaro_app.employee')),
            ],
        ),
    ]
