# Generated by Django 5.2 on 2025-05-10 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paykaro_app', '0006_remove_salary_salary_id_salary_id_payroll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='sal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='sal_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paykaro_app.employee'),
        ),
    ]
