# Generated by Django 5.2 on 2025-05-10 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paykaro_app', '0009_alter_salary_sal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='sal_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='paykaro_app.employee'),
        ),
    ]
