# Generated by Django 5.2 on 2025-05-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paykaro_app', '0010_alter_salary_sal_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='sal_id',
            new_name='sal',
        ),
    ]
