# Generated by Django 5.2 on 2025-05-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paykaro_app', '0011_rename_sal_id_salary_sal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='sal',
            new_name='sal_id',
        ),
    ]
