# Generated by Django 5.2 on 2025-05-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paykaro_app', '0012_rename_sal_salary_sal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='sal_id',
        ),
    ]
