# Generated by Django 5.2 on 2025-05-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paykaro_app', '0013_remove_salary_sal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='id',
        ),
        migrations.AddField(
            model_name='salary',
            name='salary_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
