# Generated by Django 5.2 on 2025-05-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paykaro_app', '0014_remove_salary_id_salary_salary_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='salary_id',
        ),
        migrations.AddField(
            model_name='salary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
