# Generated by Django 5.2 on 2025-05-10 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paykaro_app', '0015_remove_salary_salary_id_salary_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
