# Generated by Django 5.2 on 2025-05-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paykaro_app', '0016_delete_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.AutoField(primary_key=True, serialize=False)),
                ('basic', models.DecimalField(decimal_places=2, help_text='Basic salary', max_digits=10)),
                ('DA', models.DecimalField(decimal_places=2, help_text='Dearness Allowance', max_digits=10)),
                ('HRA', models.DecimalField(decimal_places=2, help_text='House Rent Allowance', max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, help_text='Bonus amount', max_digits=10)),
                ('income_tax', models.DecimalField(decimal_places=2, help_text='Income tax deducted', max_digits=10)),
                ('PF', models.DecimalField(decimal_places=2, help_text='Provident Fund contribution', max_digits=10)),
                ('health_ins', models.DecimalField(decimal_places=2, default=1000, help_text='Health insurance deduction', max_digits=10)),
            ],
        ),
    ]
