# Generated by Django 5.2 on 2025-05-10 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paykaro_app', '0017_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='emp_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='paykaro_app.employee'),
        ),
        migrations.DeleteModel(
            name='JobDepartment',
        ),
    ]
