# Generated by Django 5.2 on 2025-05-10 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paykaro_app', '0018_salary_emp_id_delete_jobdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('sal_range', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=15)),
                ('man_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paykaro_app.employee')),
            ],
        ),
    ]
