# Generated by Django 5.2 on 2025-05-10 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paykaro_app', '0019_job_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='dept_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paykaro_app.department'),
        ),
    ]
