# Generated by Django 5.2 on 2025-05-11 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paykaro_app', '0020_job_dept_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='man_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paykaro_app.employee'),
        ),
    ]
