# Generated by Django 5.2 on 2025-05-12 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paykaro_app', '0021_alter_department_man_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='emp_id',
        ),
    ]
