# Generated by Django 5.2 on 2025-05-12 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paykaro_app', '0022_remove_payroll_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='payroll_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paykaro_app.payroll'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='salary_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paykaro_app.salary'),
        ),
    ]
