# Generated by Django 5.2 on 2025-05-27 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paykaro_app', '0023_leave_payroll_id_payroll_salary_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dept_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paykaro_app.department'),
        ),
    ]
