# Generated by Django 5.2 on 2025-05-30 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paykaro_app', '0024_employee_dept_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='man_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='man_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paykaro_app.employee'),
        ),
    ]
